create table images (
                        id int8 generated by default as identity,
                        date_created timestamp,
                        date_updated timestamp,
                        link varchar(255),
                        album_id int8,
                        primary key (id)
);

create table places (
                        id int8 generated by default as identity,
                        date_created timestamp,
                        date_updated timestamp,
                        address varchar(255),
                        description varchar(255),
                        name varchar(255),
                        album_id int8,
                        primary key (id)
);

create table prices (
                        id int8 generated by default as identity,
                        date_created timestamp,
                        date_updated timestamp,
                        amount numeric(19, 2),
                        minute int8,
                        room_type_id int8,
                        primary key (id)
);

create table roles (
                       id int8 generated by default as identity,
                       date_created timestamp,
                       date_updated timestamp,
                       name varchar(255),
                       primary key (id)
);

create table room_types (
                            id int8 generated by default as identity,
                            date_created timestamp,
                            date_updated timestamp,
                            description varchar(255),
                            name varchar(255),
                            album_id int8,
                            place_id int8,
                            primary key (id)
);

create table users (
                       id int8 generated by default as identity,
                       date_created timestamp,
                       date_updated timestamp,
                       email varchar(255),
                       login varchar(255),
                       password varchar(255),
                       avatar_id int8,
                       role_id int8,
                       primary key (id)
);

create table with_image (
                            id int8 generated by default as identity,
                            date_created timestamp,
                            date_updated timestamp,
                            primary key (id)
);

alter table if exists images
    add constraint FKpol27y7oub18q0h0pa4f6i6cp
        foreign key (album_id)
            references with_image;

alter table if exists places
    add constraint FKdyd0m6oj147hjwtosa6dikm3
        foreign key (album_id)
            references with_image;

alter table if exists prices
    add constraint FKbvb2b3hpra7lsy9ivcuoscyh1
        foreign key (room_type_id)
            references room_types;

alter table if exists room_types
    add constraint FK8uaxp0n03jm1gba5buoqxjckk
        foreign key (album_id)
            references with_image;

alter table if exists room_types
    add constraint FKi1h0l9rxybmtddf4ovtth85j1
        foreign key (place_id)
            references places;

alter table if exists users
    add constraint FKcmbdwiv3ko3ifomgtxie1blsf
        foreign key (avatar_id)
            references with_image;

alter table if exists users
    add constraint FKp56c1712k691lhsyewcssf40f
        foreign key (role_id)
            references roles