create table images
(
    id           int8 generated by default as identity,
    date_created timestamp,
    date_updated timestamp,
    link         varchar(255),
    album_id     int8,
    primary key (id)
);


create table orders
(
    id           int8 generated by default as identity,
    date_created timestamp,
    date_updated timestamp,
    start_room   timestamp,
    room_type_id int8,
    user_id      int8,
    primary key (id)
)
;

create table places
(
    id           int8 generated by default as identity,
    date_created timestamp,
    date_updated timestamp,
    address      varchar(255),
    description  varchar(255),
    name         varchar(255),
    album_id     int8,
    primary key (id)
);


create table prices
(
    id           int8 generated by default as identity,
    date_created timestamp,
    date_updated timestamp,
    amount       numeric(19, 2),
    minute       int8,
    room_type_id int8,
    primary key (id)
);


create table roles
(
    id           int8 generated by default as identity,
    date_created timestamp,
    date_updated timestamp,
    name         varchar(255),
    primary key (id)
);


create table room_types
(
    id           int8 generated by default as identity,
    date_created timestamp,
    date_updated timestamp,
    description  varchar(255),
    name         varchar(255),
    album_id     int8,
    place_id     int8,
    primary key (id)
);


create table users
(
    id           int8 generated by default as identity,
    date_created timestamp,
    date_updated timestamp,
    email        varchar(255),
    login        varchar(255),
    password     varchar(255),
    avatar_id    int8,
    role_id      int8,
    primary key (id)
);


create table with_images
(
    id           int8 generated by default as identity,
    date_created timestamp,
    date_updated timestamp,
    primary key (id)
);


alter table if exists images
    add constraint FK905xpe7li08okbb9iinva69ks
        foreign key (album_id)
            references with_images;


alter table if exists orders
    add constraint FKr5y9h40n50cg9cq9wye4rq2pe
        foreign key (room_type_id)
            references room_types;


alter table if exists orders
    add constraint FK32ql8ubntj5uh44ph9659tiih
        foreign key (user_id)
            references users;


alter table if exists places
    add constraint FKl0uknpnl4s7yjwmx7ycbk54qm
        foreign key (album_id)
            references with_images;


alter table if exists prices
    add constraint FKbvb2b3hpra7lsy9ivcuoscyh1
        foreign key (room_type_id)
            references room_types;


alter table if exists room_types
    add constraint FKkdccair6h75wqutdb2x2e1gvn
        foreign key (album_id)
            references with_images;


alter table if exists room_types
    add constraint FKi1h0l9rxybmtddf4ovtth85j1
        foreign key (place_id)
            references places;


alter table if exists users
    add constraint FKsbs4cpy9lvuax7fxamja1cdae
        foreign key (avatar_id)
            references with_images;


alter table if exists users
    add constraint FKp56c1712k691lhsyewcssf40f
        foreign key (role_id)
            references roles;